config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :sindans
  root "one#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/one_controller.rb
class OneController < ApplicationController
    def index
    end
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index 
    end   
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/one_helper.rb
module OneHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Protest+Strike&display=swap" rel="stylesheet">

app/views/one/index.html.erb
 <div class="container">
 <div class="container2">
 <div class="title">
  NO SUBCULTURE,NO LIFE 
  </div>
  <div class="box">
  <%= image_tag "logo.png",size:'100x100' %>
  </div>
  </div>
  <div class="text">
  Let's find your favorite comics and anime
  </div>
  <div class="link">

  <%= link_to("Click Here!", sindans_path,{class:"link1"}) %>

</div>